"""replace password auth with clerk_id

Revision ID: 302d83b6a686
Revises: 193e77340319
Create Date: 2026-03-02 22:23:15.784933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302d83b6a686'
down_revision = '193e77340319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clerk_id', sa.String(length=128), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.create_unique_constraint('uq_users_clerk_id', ['clerk_id'])
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_constraint('uq_users_clerk_id', type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('clerk_id')

    # ### end Alembic commands ###
